### ISSUE TITLE
Wrong calculation of dive plan with deco gas

### ISSUE THREAD

**Issue by henrik242** [nyxtom/dive#2]
I tried creating a pretty straight forward 55m dive with 20 mins bottom time, 18/45 as the back gas and 50% o2 as deco gas.  But I think something wrong, because I should clearly have more deco than three minutes

Here it is:

    var dive = require('scuba-dive');
    var buhlmannDeco = dive.deco.buhlmann();
    var newPlan = new buhlmannDeco.plan(buhlmannDeco.ZH16ATissues);
    
    var he = 0.45;
    var o2 = 0.18;
    var n2 = 1 - he - o2;
    
    newPlan.addDepthChange(0, 55, n2, he, 2);
    newPlan.addFlat(55, n2, he, 20);
    var result = newPlan.calculateDecompression(0.5, 0.0);
    
    console.log(result);// [{'depth':3,'time':3}]

**Comment by archisgore** [comment]
There was a bug in how buhlmann was implemented. I fixed this. Please try again. Reopen if you think it's still broken.

**Comment by henrik242** [comment]
@archisgore Cool! I'll check it out.  There are a lot of unit tests for buhlmann (and vpm) in https://github.com/torvalds/subsurface/blob/master/tests/testplan.cpp, you might want to copy some of those.  And an open buhlmann/vpm implementation in https://github.com/torvalds/subsurface/blob/master/subsurface-core/deco.c :)
