### ISSUE TITLE
Problems calculating NDL

### ISSUE THREAD

**Issue by grega** [nyxtom/dive#3]
Firstly, thanks for all the work that has gone into this so far!

It appears that there's an issue in the NDL calculation relating to the ceiling. Where the ceiling starts as a negative integer and should progressively increase until > 0 (through the addition of 1min increments at depths increasing by 3m at each iteration) I'm seeing the reverse: the ceiling becomes more negative with each iteration eg. from -3 up until -24 where it gets stuck in an infinite loop. This is mirrored when running `grunt test`.

The readme seems to indicate that this particular portion may still be work-in-progress, I'd very much like to help get it back on track if possible, but could do with an initial discussion (assuming this is a somewhat known issue).

**Comment by archisgore** [comment]
I saw this today. I'm fixing it now.

**Comment by archisgore** [comment]
Fixed. NDLs match PADI tables closely (not exactly though.)

**Comment by grega** [comment]
:+1:  thanks!
